name: agile_crafts
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  # Flutter SDK and UI dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking dependencies
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # State management and functional programming
  flutter_riverpod: ^2.6.1
  dartz: ^0.10.1

  # Code generation and serialization
  freezed_annotation: ^2.4.4

  # Miscellaneous
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  form_builder_validators: ^11.0.0
  flutter_form_builder: ^9.5.0
  flutter_data: ^1.6.0
  hive_flutter: ^1.1.0

dev_dependencies:
  # Flutter testing and code generation tools
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  freezed: ^2.5.7

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
